name: Teleport Auth (Kubernetes)
author: Gravitational, Inc.
description: Authenticates your workflow so it can use tools like `kubectl` against Kubernetes clusters protected by Teleport.
inputs:
    anonymous-telemetry:
        description: Enables anonymous telemetry. See https://goteleport.com/docs/machine-id/reference/telemetry/ for more information.
        required: false
    ca-pins:
        description: Specifies one or more trusted CAs to initially validate the identity of the Auth Server when connecting directly to it. This is not required for Teleport Cloud or when connecting via a Teleport Proxy
        required: false
    certificate-ttl:
        description: Specify the length that the generated credentials should be valid for. Defaults to "1h"
        required: false
    kubernetes-cluster:
        description: Specify the name of the Kubernetes cluster in Teleport you wish to connect to.
        required: true
    proxy:
        description: Specify the address of your Teleport Proxy.
        required: true
    token:
        description: Specify the Teleport token to use to join.
        required: true
runs:
    using: node20
    main: dist/index.js
branding:
    color: purple
    icon: terminal
